### Testing get servers end point
GET http://localhost:3000/api/v1/servers HTTP/1.1


### Testing get server by id
GET http://localhost:3000/api/v1/servers/131241455 HTTP/1.1


### Testing create server
POST http://localhost:3000/api/v1/servers HTTP/1.1
Content-Type: application/json

{
    "server": {
        "serverID": "131241455",
        "serverName": "Sasa Hub"
    }
}

### Testing sending a song request
PUT http://localhost:3000/api/v1/statistics/submit HTTP/1.1
Content-Type: application/json

{
     "songRequest": {
                "serverID": "131241455",
                "songName":"Sasa lounge gamed awy"
        }
}
